import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { Suspense } from "react";
import { auth } from "../../auth";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function AuthWrapper({ children }: { children: React.ReactNode }) {
  "use client";
  const session = await auth();
  return <SessionProvider session={session}>{children}</SessionProvider>;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen flex flex-col`}
      >
        <Suspense>
          <AuthWrapper>
            <ThemeProvider attribute="class" defaultTheme="system">
              <Navbar />

              <main className="flex-grow overflow-x-hidden">{children}</main>
              <Toaster />
            </ThemeProvider>
          </AuthWrapper>
        </Suspense>
      </body>
    </html>
  );
}
